application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', "Index@index")
    ->name('home');
{//Auth
    Route::get('/login', "Authenticate@login")
        ->name("login");

    Route::post('/login', "Authenticate@authenticate");

    Route::get('/logout', "Authenticate@logout")
        ->middleware('auth')
        ->name("logout");
}
Route::resource('/company', "Company");
Route::resource('/employee', "Employee");
Route::post('/company/autocomplete', "Company@autocomplete")
    ->name('company.autocomplete');

application/app/Company.php
<?php

namespace App;

use App\Events\CompanyDeleting;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    public    $incrementing     = false;
    protected $table            = 'company';
    protected $fillable         = [
        'name',
        'email',
        'website',
    ];
    protected $dispatchesEvents = [
        'deleting' => CompanyDeleting::class,
    ];

    /**
     * @param $name
     * @param int $limit
     * @return \Illuminate\Database\Eloquent\Collection|static[]
     */
    public static function autocomplete($name, $limit = 20)
    {
        return
            self::query()
                ->select([
                    'id',
                    'name AS label',
                ])
                ->where('name', 'LIKE', $name . '%')
                ->limit($limit)
                ->get();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|Employee
     */
    public function employees()
    {
        return
            $this->hasMany('App\Employee');
    }
}

application/app/Http/Controllers/Company.php
<?php

namespace App\Http\Controllers;

use App\Http\Middleware\CompanyLogo;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class Company extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function autocomplete(Request $request)
    {
        $data = [];

        if ($request->has('name')) {
            $data =
                \App\Company::autocomplete(
                    $request->name
                );
        }

        return
            response()->json($data);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data = \App\Company::query()->paginate(10);

        return
            view('company.index', compact('data'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return
            $this->edit(new \App\Company());
    }

    /**
     * @param \App\Http\Requests\Company $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\Company $request)
    {
        $company = new \App\Company($request->validated());

        if (
            $company->save()
            && CompanyLogo::processLogo(
                $company,
                $request->file('logo')->getRealPath(),
                $request->file('logo')->getClientOriginalExtension()
            )
        ) {
            return
                redirect()
                    ->route(
                        'company.show',
                        $company,
                        302,
                        [
                            'X-Created' => 1,
                        ]
                    )
                    ->with('success', 'Company created.');
        }

        $request->flash();

        return
            redirect()
                ->route('company.create')
                ->with('error', 'Error occurred when saving a new company');
    }

    /**
     * @param \App\Company $company
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(\App\Company $company)
    {

        return
            view(
                'company.show',
                compact('company')
            );
    }

    /**
     * @param \App\Company $company
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(\App\Company $company)
    {
        return
            view(
                'company.edit',
                compact('company')
            );
    }

    /**
     * @param \App\Http\Requests\Company $request
     * @param \App\Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\Company $request, \App\Company $company)
    {
        if ($company->update($request->all())) {

            $response =
                redirect()
                    ->route(
                        'company.show',
                        $company,
                        302,
                        [
                            'X-Updated' => 1,
                        ]
                    )
                    ->with('success', 'Company updated');

            if (
                $request->hasFile('logo')
                && !CompanyLogo::processLogo(
                    $company,
                    $request->file('logo')->getRealPath(),
                    $request->file('logo')->getClientOriginalExtension()
                )
            ) {
                $response->with('warning', 'Logo not updated');
            }

            return $response;
        }

        return
            redirect()
                ->route('company.edit', $company)
                ->with('error', 'Company not updated');
    }

    /**
     * @param \App\Company $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(\App\Company $company)
    {
        if ($company->delete()) {
            return
                redirect()
                    ->route(
                        'company.index',
                        [],
                        302,
                        [
                            'X-Deleted' => 1,
                        ]
                    )
                    ->with('success', 'Company deleted');
        }

        return
            redirect()
                ->route('company.show', $company)
                ->with('error', 'Company not deleted');
    }
}

application/resources/views/company/autocomplete.blade.php
<script>
    $("{{$source}}").autocomplete({
        source   : function (request, response) {
            $.ajax({
                url    : "{{route('company.autocomplete')}}",
                type   : "POST",
                data   : {
                    name: request.term
                },
                success: function (data) {
                    if (data.length > 0) {
                        response(data);
                    }
                }
            });
        },
        minLength: 1,
        autoFocus: true,
        select   : function (event, ui) {
            $("{{$destination}}").each(function (index, value) {
                $(value).val(ui.item.id);
            });

            return true;
        }
    });
</script>

application/resources/views/company/edit.blade.php
@extends('layouts.master')

@section('title', $company->exists ? 'Edit company':'Create new company')
@section('content')
    <div class="container-fluid pt-3">
        <div class="card">
            <form method="POST"
                  action="{{ $company->exists ? route('company.update',$company):route('company.store') }}"
                  enctype="multipart/form-data">
                @if($company->exists)
                    @method('PUT')
                @endif
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input class="form-control" id="name" placeholder="Enter company name" name="name"
                               value="{{old('name',$company->name)}}">
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"
                               value="{{old('email',$company->email)}}">
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="website">Website</label>
                        <input class="form-control" id="website" placeholder="Enter website URL" name="website"
                               value="{{old('website',$company->website)}}">
                        @error('website')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="logo">Logo</label>
                        <div class="custom-file">
                            <input type="file" id="logo" name="logo" accept="image/*">
                            <label class="custom-file-label" for="logo">Choose file</label>
                        </div>
                        @error('logo')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
@stop

application/resources/views/company/index.blade.php
@extends('layouts.master')

@section('title', 'Companies list')
@section('content')
    @include('company.list',['paginate'=>true])
@stop

application/resources/views/company/list.blade.php
<div class="container-fluid pt-3">
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">Companies</h3>
            <div class="card-tools">
                <a href="{{route('company.create')}}" class="btn btn-tool btn-sm">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Website</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data as $company)
                    <tr>
                        <td>
                            <a href="{{route('company.show',$company->id)}}">
                                <img src="{{\App\Http\Middleware\CompanyLogo::getLogoThumbnailUrl($company)}}"
                                     alt="Product 1"
                                     class="img-size-32 mr-2">
                                {{$company->name}}
                            </a>
                        </td>
                        <td>
                            {{$company->website}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @if($paginate)
                <div class="card-header border-0">
                    <div class="card-tools">
                        {{$data->links()}}
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

application/resources/views/company/show.blade.php
@extends('layouts.master')

@section('title', 'Company details')
@section('content')
    <div class="container-fluid pt-3">
        <div class="row">
            <div class="col-md-12">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid" src="{{\App\Http\Middleware\CompanyLogo::getLogoUrl($company)}}"
                                 alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{$company->name}}</h3>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Email</b> <a class="float-right">{{$company->email}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Website</b> <a class="float-right">{{$company->website}}</a>
                            </li>
                        </ul>

                        <form action="{{route('company.destroy',$company->id)}}" method="POST" class="text-center">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('company.edit',$company->id)}}" class="btn btn-primary">
                                Edit
                            </a>
                            <button type="submit" class="btn btn-danger">
                               Delete
                            </button>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->

                <!-- /.card -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
    </div>
@stop