application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', "Index@index")
    ->name('home');
{//Auth
    Route::get('/login', "Authenticate@login")
        ->name("login");

    Route::post('/login', "Authenticate@authenticate");

    Route::get('/logout', "Authenticate@logout")
        ->middleware('auth')
        ->name("logout");
}
Route::resource('/company', "Company");
Route::resource('/employee', "Employee");
Route::post('/company/autocomplete', "Company@autocomplete")
    ->name('company.autocomplete');

application/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    public    $incrementing = false;
    protected $table        = 'employee';
    protected $with         = ['company'];
    protected $fillable     = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'company_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo|Company
     */
    public function company()
    {
        return
            $this->belongsTo('App\Company');
    }
}

application/app/Http/Controllers/Employee.php
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller;

class Employee extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data = \App\Employee::query()->paginate(10);

        return
            view('employee.index', compact('data'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return
            $this->edit(new \App\Employee());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Employee $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\Employee $request)
    {
        if (($employee = new \App\Employee($request->validated()))->save()) {
            return
                redirect()
                    ->route(
                        'employee.show',
                        $employee,
                        302,
                        [
                            'X-Created' => 1,
                        ]
                    )
                    ->with('success', 'Employee created.');
        }

        $request->flash();

        return
            redirect()
                ->route('employee.create')
                ->with('error', 'Error occurred when saving a new employee');
    }

    /**
     * @param \App\Employee $employee
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(\App\Employee $employee)
    {
        return
            view(
                'employee.show',
                compact('employee')
            );
    }

    /**
     * @param \App\Employee $employee
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(\App\Employee $employee)
    {
        return
            view(
                'employee.edit',
                compact('employee')
            );
    }

    /**
     * @param \App\Http\Requests\Employee $request
     * @param \App\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\Employee $request, \App\Employee $employee)
    {
        if ($employee->update($request->all())) {
            return
                redirect()
                    ->route(
                        'employee.show',
                        $employee,
                        302,
                        [
                            'X-Updated' => 1,
                        ]
                    )
                    ->with('success', 'Employee updated');
        }

        return
            redirect()
                ->route('employee.edit', $employee)
                ->with('error', 'Employee not updated');
    }

    /**
     * @param \App\Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(\App\Employee $employee)
    {
        if ($employee->delete()) {
            return
                redirect()
                    ->route(
                        'employee.index',
                        [],
                        302,
                        [
                            'X-Deleted' => 1,
                        ]
                    )
                    ->with('success', 'Employee deleted');
        }

        return
            redirect()
                ->route('employee.show', $employee)
                ->with('error', 'Employee not deleted');
    }
}

application/resources/views/employee/edit.blade.php
@extends('layouts.master')
@section('title', $employee->exists ? 'Edit employee':'Create new employee')

@section('content')
    <div class="container-fluid pt-3">
        <div class="card">
            <form method="POST"
                  action="{{ $employee->exists ? route('employee.update',$employee):route('employee.store') }}">

                @if($employee->exists)
                    @method('PUT')
                @endif
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="company">Company</label>
                        <input class="form-control" id="company" placeholder="Enter company" name="company"
                               value="{{old('company',$employee->company()->getResults()?$employee->company()->getResults()->name:'')}}">
                        <input id="companyId" type="hidden" name="company_id"
                               value="{{old('company_id',$employee->company()->getResults()?$employee->company()->getResults()->id:'')}}">
                        @error('company_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="firstName">First name</label>
                        <input class="form-control" id="firstName" placeholder="Enter first name" name="first_name"
                               value="{{old('first_name',$employee->first_name)}}">
                        @error('first_name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="lastName">Last name</label>
                        <input class="form-control" id="lastName" placeholder="Enter last name" name="last_name"
                               value="{{old('last_name',$employee->last_name)}}">
                        @error('last_name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"
                               value="{{old('email',$employee->email)}}">
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input class="form-control" id="phone" placeholder="Enter phone" name="phone"
                               value="{{old('phone',$employee->phone)}}">
                        @error('phone')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
    @include('company.autocomplete',['source'=>'#company','destination'=>'#companyId'])
@stop

application/resources/views/employee/index.blade.php
@extends('layouts.master')

@section('title', 'Employees list')
@section('content')
    @include('employee.list',['paginate'=>true])
@stop

application/resources/views/employee/list.blade.php
<div class="container-fluid pt-3">
    <div class="card">
        <div class="card-header border-0">
            <h3 class="card-title">Employees</h3>
            <div class="card-tools">
                <a href="{{route('employee.create')}}" class="btn btn-tool btn-sm">
                    <i class="fa fa-user-plus"></i>
                </a>
            </div>
        </div>
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-valign-middle">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Company</th>
                    <th>Email</th>
                    <th>Phone</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data as $employee)
                    <tr>
                        <td>
                            <a href="{{route('employee.show',$employee->id)}}">
                                {{$employee->first_name}} {{$employee->last_name}}
                            </a>
                        </td>
                        <td>
                            <a href="{{route('company.show',$employee->company()->getResults()->id)}}">
                                {{$employee->company()->getResults()->name}}
                            </a>
                        </td>
                        <td>
                            {{$employee->email}}
                        </td>
                        <td>
                            {{$employee->phone}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            @if($paginate)
                <div class="card-header border-0">
                    <div class="card-tools">
                        {{$data->links()}}
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>

application/resources/views/employee/show.blade.php
@extends('layouts.master')

@section('title', 'Employee details')
@section('content')
    <div class="container-fluid pt-3">
        <div class="row">
            <div class="col-md-12">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src="../../dist/img/avatar.png"
                                 alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{$employee->first_name}} {{$employee->last_name}}</h3>

                        <p class="text-muted text-center">{{$employee->company()->getResults()->name}}</p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Email</b> <a class="float-right">{{$employee->email}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Phone</b> <a class="float-right">  {{$employee->phone}}</a>
                            </li>
                        </ul>

                        <form action="{{route('employee.destroy',$employee->id)}}" method="POST" class="text-center">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('employee.edit',$employee->id)}}" class="btn btn-primary">
                                Edit
                            </a>
                            <button type="submit" class="btn btn-danger">
                               Delete
                            </button>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->

                <!-- /.card -->
            </div>
            <!-- /.col -->

            <!-- /.col -->
        </div>
    </div>
@stop